# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yangzij/CLionProjects/untitled5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yangzij/CLionProjects/untitled5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yangzij/CLionProjects/untitled5/CMakeFiles /Users/yangzij/CLionProjects/untitled5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yangzij/CLionProjects/untitled5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named untitled5

# Build rule for target.
untitled5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 untitled5
.PHONY : untitled5

# fast build rule for target.
untitled5/fast:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/build
.PHONY : untitled5/fast

Alloctor.o: Alloctor.cpp.o

.PHONY : Alloctor.o

# target to build an object file
Alloctor.cpp.o:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Alloctor.cpp.o
.PHONY : Alloctor.cpp.o

Alloctor.i: Alloctor.cpp.i

.PHONY : Alloctor.i

# target to preprocess a source file
Alloctor.cpp.i:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Alloctor.cpp.i
.PHONY : Alloctor.cpp.i

Alloctor.s: Alloctor.cpp.s

.PHONY : Alloctor.s

# target to generate assembly for a file
Alloctor.cpp.s:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Alloctor.cpp.s
.PHONY : Alloctor.cpp.s

Cleaup.o: Cleaup.cpp.o

.PHONY : Cleaup.o

# target to build an object file
Cleaup.cpp.o:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Cleaup.cpp.o
.PHONY : Cleaup.cpp.o

Cleaup.i: Cleaup.cpp.i

.PHONY : Cleaup.i

# target to preprocess a source file
Cleaup.cpp.i:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Cleaup.cpp.i
.PHONY : Cleaup.cpp.i

Cleaup.s: Cleaup.cpp.s

.PHONY : Cleaup.s

# target to generate assembly for a file
Cleaup.cpp.s:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Cleaup.cpp.s
.PHONY : Cleaup.cpp.s

Exception.o: Exception.cpp.o

.PHONY : Exception.o

# target to build an object file
Exception.cpp.o:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Exception.cpp.o
.PHONY : Exception.cpp.o

Exception.i: Exception.cpp.i

.PHONY : Exception.i

# target to preprocess a source file
Exception.cpp.i:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Exception.cpp.i
.PHONY : Exception.cpp.i

Exception.s: Exception.cpp.s

.PHONY : Exception.s

# target to generate assembly for a file
Exception.cpp.s:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Exception.cpp.s
.PHONY : Exception.cpp.s

Pool.o: Pool.cpp.o

.PHONY : Pool.o

# target to build an object file
Pool.cpp.o:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Pool.cpp.o
.PHONY : Pool.cpp.o

Pool.i: Pool.cpp.i

.PHONY : Pool.i

# target to preprocess a source file
Pool.cpp.i:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Pool.cpp.i
.PHONY : Pool.cpp.i

Pool.s: Pool.cpp.s

.PHONY : Pool.s

# target to generate assembly for a file
Pool.cpp.s:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Pool.cpp.s
.PHONY : Pool.cpp.s

UnsetValue.o: UnsetValue.cpp.o

.PHONY : UnsetValue.o

# target to build an object file
UnsetValue.cpp.o:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/UnsetValue.cpp.o
.PHONY : UnsetValue.cpp.o

UnsetValue.i: UnsetValue.cpp.i

.PHONY : UnsetValue.i

# target to preprocess a source file
UnsetValue.cpp.i:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/UnsetValue.cpp.i
.PHONY : UnsetValue.cpp.i

UnsetValue.s: UnsetValue.cpp.s

.PHONY : UnsetValue.s

# target to generate assembly for a file
UnsetValue.cpp.s:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/UnsetValue.cpp.s
.PHONY : UnsetValue.cpp.s

Value.o: Value.cpp.o

.PHONY : Value.o

# target to build an object file
Value.cpp.o:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Value.cpp.o
.PHONY : Value.cpp.o

Value.i: Value.cpp.i

.PHONY : Value.i

# target to preprocess a source file
Value.cpp.i:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Value.cpp.i
.PHONY : Value.cpp.i

Value.s: Value.cpp.s

.PHONY : Value.s

# target to generate assembly for a file
Value.cpp.s:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Value.cpp.s
.PHONY : Value.cpp.s

Wrapper.o: Wrapper.cpp.o

.PHONY : Wrapper.o

# target to build an object file
Wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Wrapper.cpp.o
.PHONY : Wrapper.cpp.o

Wrapper.i: Wrapper.cpp.i

.PHONY : Wrapper.i

# target to preprocess a source file
Wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Wrapper.cpp.i
.PHONY : Wrapper.cpp.i

Wrapper.s: Wrapper.cpp.s

.PHONY : Wrapper.s

# target to generate assembly for a file
Wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/Wrapper.cpp.s
.PHONY : Wrapper.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/untitled5.dir/build.make CMakeFiles/untitled5.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... untitled5"
	@echo "... Alloctor.o"
	@echo "... Alloctor.i"
	@echo "... Alloctor.s"
	@echo "... Cleaup.o"
	@echo "... Cleaup.i"
	@echo "... Cleaup.s"
	@echo "... Exception.o"
	@echo "... Exception.i"
	@echo "... Exception.s"
	@echo "... Pool.o"
	@echo "... Pool.i"
	@echo "... Pool.s"
	@echo "... UnsetValue.o"
	@echo "... UnsetValue.i"
	@echo "... UnsetValue.s"
	@echo "... Value.o"
	@echo "... Value.i"
	@echo "... Value.s"
	@echo "... Wrapper.o"
	@echo "... Wrapper.i"
	@echo "... Wrapper.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

